### ISSUE TITLE
Instruction Clarity

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/phase-3-reading-python-error-messages#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195258?module_item_id=439007

### Concern

It might be helpful to remind students that they need to run `pipenv shell` before they're able to run `pytest` in the instructions section for this lab. This is unfamiliar to students who are used to just running `learn test` from the command line, and could probably use some reiteration during these early labs. I can see students get hung up on this as is.

**Comment by professor-ben** [comment]
I agree- some others mentioned this as well in the phase3-builds channel. This is more of a broad change, so we will include it in all labs moving forward and loop back around to include these in the early labs at the end of this build.
